# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

name: Deploy Bicep files

variables:
  vmImageName: 'ubuntu-latest'

  azureServiceConnection: 'Prod_Subscription'
  location: 'australiaeast'
  templateFile: '/main.bicep'
  templateParameterFile: '/main.parameters.json'
  resourceGroupName: 'RG-Bicep-Adb'

pool:
  vmImage: $(vmImageName)

stages:  

- stage: Preview
  jobs: 
  - job: Preview
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: '$(azureServiceConnection)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az deployment group what-if \
            --template-file $(Build.SourcesDirectory)/$(templateFile) \
            --parameters '$(Build.SourcesDirectory)/$(templateParameterFile)' \
            --resource-group '$(resourceGroupName)'

- stage: Deploy
  jobs:
  - job: Deploy
    steps:
      - task: AzureResourceManagerTemplateDeployment@3
        displayName: 'Deploy Bicep Files'
        inputs:
          deploymentScope: 'Resource Group'
          resourceGroupName: '$(resourceGroupName)'
          azureResourceManagerConnection: '$(azureServiceConnection)'
          action: 'Create Or Update Resource Group'
          location: '$(location)'
          csmFile: '$(Build.SourcesDirectory)/$(templateFile)'
          csmParametersFile: '$(Build.SourcesDirectory)/$(templateParameterFile)'
          deploymentMode: 'Incremental'
          deploymentName: 'DeployPipelineTemplate'
